# -*- coding: utf-8 -*-
"""Python-task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HTeKbU3sfRe9xa-HNCCdsJKAC-XzwzaA
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

# Load dataset
df = pd.read_csv('Titanic-Dataset.csv')

# Display first 5 rows
print(df.head())

# Display dataset structure and missing values
print(df.info())

df.isnull().sum()

df['Age'].fillna(df['Age'].median(), inplace=True)
df['Age'] = df.groupby(['Pclass','Sex'])['Age'].transform(lambda x: x.fillna(x.median()))

df.drop(columns=['Cabin'], inplace=True, errors='ignore')
if 'Cabin' in df.columns:
    df.drop(columns=['Cabin'], inplace=True)
    df['Deck'] = df['Cabin'].str[0]

# Fills the column and reassigns it explicitly
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

print(df.info())
df.isnull().sum()

print("Before removing duplicates:", df.shape[0])

print("Number of duplicate rows:", df.duplicated().sum())

df.drop_duplicates(inplace=True)

print("After removing duplicates:", df.shape[0])

df.dtypes #Check Current Datatypes

df['Survived'] = df['Survived'].astype(bool)
df['Pclass'] = df['Pclass'].astype('category')
df['Sex'] = df['Sex'].astype('category')
#df['BookingDate'] = pd.to_datetime(df['BookingDate'])

df.dtypes

def age_category(age):
    if age < 12:
        return 'Child'
    elif age < 18:
        return 'Teen'
    elif age < 60:
        return 'Adult'
    else:
        return 'Senior'

df['AgeGroup'] = df['Age'].apply(age_category)
df[['Age', 'AgeGroup']].head()

df['AgeGroup'].value_counts()

df['FareBand'] = pd.qcut(df['Fare'], 4, labels=['Low','Medium','High','Very High'])
df[['Fare', 'FareBand']].head()

print(df['FareBand'].value_counts())

df['FamilySize'] = df['SibSp'] + df['Parch'] + 1
df[['SibSp', 'FamilySize']].head()

df[['SibSp', 'FamilySize']].value_counts()

df['IsAlone'] = (df['FamilySize'] == 1).astype(int)
df[['FamilySize', 'IsAlone']].head()

df[['Age','AgeGroup','Fare','FareBand','FamilySize','IsAlone']].head()

df.to_csv('titanic_cleaned.csv', index=False)
from google.colab import files
files.download('titanic_cleaned.csv')
import os
os.listdir()

"""### 1. Dataset Loading
The Titanic dataset was loaded into the notebook using `pandas.read_csv()` to begin preprocessing and analysis.

### 2. Missing Value Identification
Missing values were identified using `.isnull().sum()` to determine which columns required cleaning.

### 3. Handling Missing Values
- Numerical column **Age** was filled using the median (and group-wise median for better accuracy).
- Categorical column **Embarked** was filled using the mode.
- Column **Cabin** was removed due to excessive missing values.

### 4. Duplicate Record Removal
Duplicate rows were checked using `.duplicated()` and removed using `.drop_duplicates()` to ensure data quality.

### 5. Datatype Conversion
Relevant columns were converted into appropriate datatypes using `.astype()` to support accurate calculations and efficient memory usage.

### 6. Feature Engineering
New columns such as **FamilySize**, **IsAlone**, **AgeGroup**, and **FareBand** were created to improve interpretability and predictive performance.

### 7. Data Verification
The dataset was rechecked for missing values and duplicates to confirm successful cleaning.

### 8. Saving Cleaned Dataset
The final cleaned dataset was saved as **cleaned_data.csv** using `.to_csv()` for reproducibility and further analysis.

### 9. Outcome
The processed dataset is clean, structured, and ready for exploratory data analysis and machine learning modeling.

"""